addSbtPlugin("com.github.sbt"     % "sbt-boilerplate"          % "0.7.0")
addSbtPlugin("net.virtual-void"   % "sbt-dependency-graph"     % "0.10.0-RC1")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.19.0")
addSbtPlugin("org.typelevel"      % "sbt-typelevel"            % "0.8.0")
addSbtPlugin("org.typelevel"      % "sbt-typelevel-mergify"    % "0.8.0")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"            % "2.3.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"                  % "0.4.7")
